apiVersion: v2
name: sonarr
description: sonarr helm chart for Kubernetes
type: application
version: 0.1.2
# image: linuxserver/sonarr
appVersion: "4.0.3"
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/Sonarr/Sonarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169