apiVersion: v2
name: bazarr
description: bazarr helm chart for Kubernetes
type: application
version: 0.1.1
# image: linuxserver/bazarr
appVersion: "1.4.2-ls244"
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/morpheus65535/bazarr
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169