apiVersion: v2
name: as212510-net
description: as212510.net helm chart for Kubernetes
type: application
version: 0.3.1
appVersion: "2.1.0"
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/as212510-net
home: https://github.com/M0NsTeRRR/as212510.net
icon: https://github.com/M0NsTeRRR/helm-charts/tree/main/icons/unicornafk.svg