{{- if .Values.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "prometheus-pve-exporter.fullname" . }}
  labels:
    {{- include "prometheus-pve-exporter.labels" . | nindent 4 }}
spec:
  groups:
    - name: PVEAlerts
      rules:
        - alert: PVEExporterDown
          expr: up{job="prometheus-pve-exporter-metrics"} != 1
          for: 5m
          labels:
            severity: critical
          annotations:
            description: 'PVE exporter instance {{$labels.instance}} from job {{$labels.job}} is down.'
            summary: PVE exporter instance down.
        - alert: PveNodeDown
          expr: pve_node_info{id=~"node/.*"} != 1
          for: 5m
          labels:
            severity: critical
          annotations:
            description: 'PVE node {{`{{`}}$labels.instance{{`}}`}} from job {{`{{`}}$labels.job{{`}}`}} is down.'
            summary: PVE node down.
{{- end }}