apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: qbittorrent
description: qbittorrent helm chart for Kubernetes
type: application
version: 0.2.9
# image: ghcr.io/qbittorrent/docker-qbittorrent-nox
appVersion: "4.6.4-1"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/radarr
home: https://github.com/qbittorrent/qBittorrent
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169