apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "overseerr.configPersistenceName" . }}
  labels:
    {{- include "overseerr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.config.persistence.storageClass }}
  storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.config.persistence.size }}"