name: Lint and Test Charts
on:
  - push
  - pull_request
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.0
